name = "rustworker"
main = "build/rustworker.js"
compatibility_date = "2025-11-01"

[build]
command = "./build.sh"

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyDurableObject"]
